references:
  GRCh38_chr21:
    GIABTRURL: https://giab-data.s3.amazonaws.com/giab-test-data/GRCh38chr21subset_AllTandemRepeats.bed.gz 
    REFURL: https://giab-data.s3.amazonaws.com/giab-test-data/GRCh38_chr21.fa.gz
    REF_MD5: d10eebe06c0dbbcb04253e3294d63efc
    GIABTR_MD5: 113eab8433fbae8db100efe5148fb74a
n_splits: 1
rm_threads: 1

