references:
  GRCh37: ## Will want to limit to chr21
    GIABTRURL: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.3/GRCh37@all/LowComplexity/GRCh37_AllTandemRepeats.bed.gz
    REFURL: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh37/hs37d5.fa.gz
    REF_MD5: d10eebe06c0dbbcb04253e3294d63efc
    GIABTR_MD5: 0404a18d3946d011231d49ae215ba9eb
n_splits: 4

