name: Linting
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2 
      
    - name: Display the path
      shell: bash
      run:  echo $PATH
      
    - name: Display the working directory
      shell: bash
      run: echo $PWD
        
    - name: Display the directory contents
      shell: bash
      run: ls data

    - name: Test linting
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"